trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: Pipelines variables

name: $(Major).$(Minor)-open

steps:

- checkout: self
  persistCredentials: true
- task: CmdLine@2
  displayName: 'Creating new release branch'
  inputs:
    script: |      
      git fetch
      git checkout devel
      git branch release/$(Major).$(Minor)
      git checkout release/$(Major).$(Minor)
      git push --set-upstream origin release/$(Major).$(Minor)
    failOnStderr: false