
trigger:
  branches:
    include:    
    - devel  

pool:
  vmImage: 'windows-latest'

variables:
- group: Pipelines variables  
- name: 'patch'
  value: $[counter(variables['Minor'], 0)] #this will reset when we bump minor  
- name: 'NugetVersionBeta'
  value : $(Major).$(Minor).$(patch)-beta


name: $(Major).$(Minor).$(patch)

steps:
- task: NuGetToolInstaller@1
  displayName: 'Installing nuget tool'

- task: NuGetCommand@2
  displayName: 'Restoring nugets'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Packing library'
  condition: succeeded()
  inputs:
    command: 'pack'
    packagesToPack: '**/Azure.Pipelines.Package.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'NugetVersionBeta'

- task: DotNetCoreCLI@2
  displayName: 'Pushing packages'
  condition: and( succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '1cc2e30c-e568-415d-bb34-644a12140b44'